Fix the rsync exit status handling

diff --git a/bontmia b/bontmia
--- a/bontmia
+++ b/bontmia
@@ -357,12 +357,12 @@ make_backup()
         if test "x${dryrun}" == "xno"; then
             mkdir -p "${tmpdir}/unfinished_backup/${this_backup}/${hostname}"
 
-            rsync_exit_status=0
             rsync ${rsync_options} ${excludefrom:+--exclude-from="$excludefrom"} ${linkdest:+--link-dest="${linkdest}"} \
                   -T "${tmpdir}" ${rsyncpath:+--rsync-path="${rsyncpath}"} -e "ssh $cipher -p $port $identity"          \
                   "${dir}/" "${tmpdir}/unfinished_backup/$this_backup/${hostname}" 2>&1 >/tmp/bontmia_rsync_output.$$ || {
+                rsync_exit_status=$?
                 echo
-                echo "  Caught an error doing rsync (return code $?)"
+                echo "  Caught an error doing rsync (return code ${rsync_exit_status})"
                 echo "  The last 10 lines of output from rsync:"
                 tail -10 /tmp/bontmia_rsync_output.$$
                 echo
@@ -371,27 +371,32 @@ make_backup()
                       -T "${tmpdir}" ${rsyncpath:+--rsync-path="${rsyncpath}"} -e "ssh $cipher -p $port $identity"          \
                       "${dir}/" "${tmpdir}/unfinished_backup/$this_backup/${hostname}" 2>&1 >/tmp/bontmia_rsync_output.$$.2 || {
                     rsync_exit_status=$?
-                    echo
-                    echo "  Still no luck. Rsync failed with returncode $?"
-                    echo "  ${dir}"
-                    echo "  Please check that there is room for all the data"
-                    echo "  The last 10 lines of output from rsync:"
-                    tail -10 /tmp/bontmia_rsync_output.$$.2
-                    echo
-                    echo
-                    echo "  Continuing with the next backup source"
-                    echo
-                    exit_status=1
+                    # The backup is considered successfull, even if some files have vanished during the transfer
+                    if [[ $rsync_exit_status != 24 ]]; then
+                        exit_status=1
+                        echo
+                        echo "  Still no luck. Rsync failed with returncode ${rsync_exit_status}"
+                        echo "  ${dir}"
+                        echo "  Please check that there is room for all the data"
+                        echo "  The last 10 lines of output from rsync:"
+                        tail -10 /tmp/bontmia_rsync_output.$$.2
+                        echo
+
+                        # Stop the backup, and clean
+                        break
+                    fi
                 }
             }
         fi
+        echo
+        echo "  Continuing with the next backup source"
+        echo
     done
 
-    # The backup is considered successfull, even if some files have vanished during the transfer
-    if [[ $rsync_exit_status == 0 || $rsync_exit_status == 24 ]]; then
+    if [[ $exit_status == 0 ]]; then
         moving_complete_backup_into_archive
     else
-        echo "  rsync failed twice, removing the unfinished backup"
+        echo "  rsync failed, removing the unfinished backup"
     fi
 
     if test "x${dryrun}" == "xno"; then
